import * as THREE from 'three';
export function createAlpineLife(scene,mountains){
 const group=new THREE.Group();group.name='Forested mountains and animal ski slopes';scene.add(group);mountains.group.updateMatrixWorld(true);
 const ray=new THREE.Raycaster();function height(x,z){ray.set(new THREE.Vector3(x,240,z),new THREE.Vector3(0,-1,0));return ray.intersectObjects(mountains.bands,false)[0]?.point.y;}
 let seed=137;const random=()=>{seed=(1664525*seed+1013904223)>>>0;return seed/4294967296;};
 const pineMat=new THREE.MeshStandardMaterial({color:0x52735c,roughness:1}),snowMat=new THREE.MeshStandardMaterial({color:0xeff2e9,roughness:1});
 const trunks=new THREE.InstancedMesh(new THREE.CylinderGeometry(.16,.25,1.8,5),new THREE.MeshStandardMaterial({color:0x76624e}),1500),crowns=new THREE.InstancedMesh(new THREE.ConeGeometry(1.35,4.5,7),pineMat,1500),caps=new THREE.InstancedMesh(new THREE.ConeGeometry(1.17,3.7,7),snowMat,1500);const dummy=new THREE.Object3D();let count=0;
 for(let i=0;i<2600&&count<1500;i++){const a=random()*Math.PI*2,r=12+random()*137,x=Math.cos(a)*(134+r),z=30+Math.sin(a)*(143+r);if(x>7&&x<38&&z>-148&&z<-128)continue;if(Math.abs(x)<15&&z<-118&&z>-146)continue;const y=height(x,z);if(y===undefined||y<7||y>115)continue;const scale=.7+random()*.8;dummy.position.set(x,y+.7*scale,z);dummy.scale.setScalar(scale);dummy.updateMatrix();trunks.setMatrixAt(count,dummy.matrix);dummy.position.y=y+2.7*scale;dummy.updateMatrix();crowns.setMatrixAt(count,dummy.matrix);dummy.position.y=y+3.17*scale;dummy.updateMatrix();caps.setMatrixAt(count,dummy.matrix);count++;}
 for(const mesh of [trunks,crowns,caps]){mesh.count=count;mesh.instanceMatrix.needsUpdate=true;group.add(mesh);}caps.visible=false;
 const piste=new THREE.Group();group.add(piste);const skiers=[];const white=new THREE.MeshStandardMaterial({color:0xf6e8d7,roughness:.9});
 function ball(parent,p,s,m){const o=new THREE.Mesh(new THREE.SphereGeometry(1,12,8),m);o.position.set(...p);o.scale.set(...s);parent.add(o);return o;}
 const track=[];for(let i=0;i<=80;i++){const t=i/80,x=Math.sin(t*Math.PI*3)*5,z=-139+t*19;track.push(new THREE.Vector3(x,(height(x,z)||0)+.12,z));}const curve=new THREE.CatmullRomCurve3(track);
 for(let i=0;i<6;i++){const animal=new THREE.Group();piste.add(animal);const coat=new THREE.MeshStandardMaterial({color:[0xb95e65,0x5e95af,0xd7ad53,0x9b85b6,0x749b82,0xd8876f][i]});ball(animal,[0,.74,0],[.38,.5,.28],coat);ball(animal,[0,1.32,-.08],[.36,.34,.31],white);for(const side of [-1,1]){ball(animal,[side*.2,i%2?1.62:1.83,-.06],i%2?[.13,.14,.11]:[.105,.35,.1],white);ball(animal,[side*.12,1.35,-.375],[.035,.045,.018],new THREE.MeshBasicMaterial({color:0x473b46}));const ski=new THREE.Mesh(new THREE.BoxGeometry(.14,.06,1.5),coat);ski.position.set(side*.25,.08,0);animal.add(ski);const pole=new THREE.Mesh(new THREE.CylinderGeometry(.018,.018,1.1,6),white);pole.position.set(side*.52,.57,.15);pole.rotation.x=-.3;animal.add(pole);}skiers.push(animal);}
 const points=[];for(let i=0;i<350;i++)points.push((random()-.5)*44,random()*30,-145+random()*40);const snowGeo=new THREE.BufferGeometry();snowGeo.setAttribute('position',new THREE.Float32BufferAttribute(points,3));const snowfall=new THREE.Points(snowGeo,new THREE.PointsMaterial({color:0xffffff,size:.14,transparent:true,opacity:.8}));piste.add(snowfall);
 const snowBases=points.filter((_,i)=>i%3===0).map((x,i)=>height(x,points[i*3+2])||0);
 let season='';return {group,count,skiers,curve,update(current,time=0){if(current!==season){season=current;caps.visible=current==='winter';piste.visible=current==='winter';pineMat.color.setHex(current==='winter'?0x718c80:current==='autumn'?0x748267:0x52735c);}if(!piste.visible)return;skiers.forEach((o,i)=>{const t=(time*.022+i/6)%1,p=curve.getPointAt(t),next=curve.getPointAt(Math.min(.9999,t+.008));o.position.copy(p);o.rotation.y=Math.atan2(p.x-next.x,p.z-next.z);o.rotation.x=Math.atan2(next.y-p.y,Math.hypot(next.x-p.x,next.z-p.z));o.rotation.z=Math.sin(time*2+i)*.1;});const p=snowGeo.attributes.position;for(let i=0;i<p.count;i++){const base=snowBases[i];p.setY(i,base+2+((points[i*3+1]-time*1.1)%28+28)%28);}p.needsUpdate=true;}};
}
