import * as THREE from 'three';

export function createPlayerLife(scene,farm,economy,{camera,controls,blocked,pathfind,groundHeight,rabbits,setMode,getMode,getHour,setHour,setSeason}){
 let chosen=0,player=rabbits[0].root,feet=rabbits[0].feet;
 const mat=c=>new THREE.MeshStandardMaterial({color:c,roughness:.85});
 const held=new THREE.Mesh(new THREE.BoxGeometry(.045,.28,.06),mat(0xb68955));held.position.set(.25,.35,-.14);player.add(held);
 const hand=held;
 const bed=new THREE.Mesh(new THREE.BoxGeometry(1.2,.32,1.8),mat(0xcbb9a5));bed.position.set(-28,.28,21);scene.add(bed);const blanket=new THREE.Mesh(new THREE.BoxGeometry(1.15,.12,1.1),mat(0x85aab0));blanket.position.set(-28,.48,21.3);scene.add(blanket);
 const bin=new THREE.Mesh(new THREE.BoxGeometry(.8,.8,.8),mat(0xb58353));bin.position.set(-28,.5,17);scene.add(bin);
 const board=new THREE.Mesh(new THREE.BoxGeometry(1,.85,.12),mat(0xe0c58c));board.position.set(-34,1,20.5);scene.add(board);
 const style=document.createElement('style');style.textContent=`#play-hud{position:fixed;inset:0;pointer-events:none;z-index:4;font-size:13px}#play-hud button,#play-hud dialog,#play-hud [data-stick]{pointer-events:auto}#play-top{position:absolute;left:12px;top:12px;background:#fff6e3ed;border:2px solid #af8c5e;border-radius:12px;padding:10px;max-width:68vw}#play-toolbar{position:absolute;bottom:16px;left:50%;transform:translateX(-50%);display:flex;gap:5px;background:#fff2d9ef;border:2px solid #af8c5e;border-radius:12px;padding:7px}#play-toolbar button{min-width:58px;min-height:48px;white-space:nowrap}#play-prompt{position:absolute;bottom:89px;left:50%;transform:translateX(-50%);background:#fff6e3ed;padding:9px 15px;border-radius:10px;max-width:70vw;text-align:center}#play-controls{position:absolute;right:15px;bottom:115px;display:flex;gap:8px}#play-controls button{min-height:52px;min-width:65px}#play-hud [data-stick]{position:absolute;bottom:110px;left:18px;width:100px;height:100px;border:3px solid #d6c6a1;border-radius:50%;background:#fff6e380;touch-action:none;display:grid;place-items:center}#play-hud [data-knob]{width:38px;height:38px;background:#8e9f77;border-radius:50%;pointer-events:none}#play-hud dialog{max-width:min(90vw,420px);border:2px solid #ad8b61;border-radius:14px;background:#fff5df;color:#51452e}#play-hud dialog::backdrop{background:#15201966}.playing-town header,.playing-town #bottom{display:none}.playing-town #panel details,.playing-town #panel>button,.playing-town #panel>.seasons,.playing-town #panel>small,.playing-town #season-caption{display:none}.playing-town #panel details:has(#music){display:block}#play-hud[hidden]{display:none}@media(max-width:600px){#play-toolbar{bottom:8px;gap:2px;padding:4px}#play-toolbar button{min-width:43px;padding:5px;font-size:11px}#play-prompt{bottom:75px;font-size:11px}#play-top{font-size:11px;padding:8px}}`;document.head.append(style);
 const hud=document.createElement('div');hud.id='play-hud';hud.innerHTML='<div id="play-top"><b>兔兔海岛生活</b><div><button data-rabbit="0">小白</button><button data-rabbit="2">豆豆</button><button data-rabbit="1">奶糖</button></div><div data-calendar></div><div data-energy></div><button data-bag>背包 · B</button> <button data-observe>观察小镇</button></div><div id="play-prompt" role="status"></div><div id="play-toolbar"></div><div data-stick aria-label="移动摇杆"><div data-knob></div></div><div id="play-controls"><button data-use>使用 · 空格</button><button data-interact>互动 · E</button></div><dialog><h3 data-title></h3><div data-body></div><div data-options class="row"></div><button data-close>关闭</button></dialog>';document.body.append(hud);
 const start=document.createElement('button');start.textContent='开始我的海岛生活';document.getElementById('panel').prepend(start);
 const tools=[['hoe','锄头'],['plant','种子'],['water','水壶'],['harvest','采收'],['hand','空手']];let tool='hoe',active=false,path=[],clock=0,cooldown=0,ui=0,stick={x:0,y:0},shipping=0,tilled=Array(6).fill(false),wasActive=false;
 try{const s=JSON.parse(localStorage.getItem('bunny-player-life-v1'));if(s){shipping=Math.max(0,Math.floor(Number(s.shipping)||0));if(s.tilled?.length===6)tilled=s.tilled.map(Boolean);}}catch{}
 const save=()=>{farm.save();try{localStorage.setItem('bunny-player-life-v1',JSON.stringify({shipping,tilled,position:[player.position.x,player.position.z]}));}catch{}};
 const keyset=new Set(),dialog=hud.querySelector('dialog');
 function near(x,z,r=2){return Math.hypot(player.position.x-x,player.position.z-z)<r;}
 function nearestPlot(){let index=-1,d=1.85;farm.plots.forEach((p,i)=>{const q=player.position.distanceTo(p.bed.position);if(q<d){index=i;d=q;}});return index;}
 const spots={buy:[-40,30],sell:[47,-5],reward:[-34,20.5],rest:[-28,21],build:[-38,22],shipping:[-28,17]};
 farm.setAccess((type,i)=>active&&!dialog.open&&(type==='plot'?player.position.distanceTo(farm.plots[i].bed.position)<1.85:spots[type]&&near(...spots[type])));
 const clearedTrees=[];scene.updateMatrixWorld(true);scene.traverse(o=>{if(o.isMesh&&/olive|tree|trunk/i.test(o.name)){const p=o.getWorldPosition(new THREE.Vector3());if(Math.abs(p.x+31.7)<4&&Math.abs(p.z-17.6)<4)clearedTrees.push(o);}});
 const notice=t=>{hud.querySelector('#play-prompt').textContent=t;ui=-3;};
 function select(t){tool=t;hud.querySelectorAll('[data-slot]').forEach(b=>b.classList.toggle('active',b.dataset.slot===t));held.visible=t!=='hand';held.material.color.set(t==='water'?0x6bacc0:t==='plant'?0x83a368:0xb68955);}
 tools.forEach(([t,label],i)=>{const b=document.createElement('button');b.dataset.slot=t;b.textContent=`${i+1} ${label}`;b.onclick=()=>select(t);hud.querySelector('#play-toolbar').append(b);});select('hoe');
 function show(title,text,actions=[]){keyset.clear();stick={x:0,y:0};path=[];hud.querySelector('[data-title]').textContent=title;hud.querySelector('[data-body]').textContent=text;const row=hud.querySelector('[data-options]');row.replaceChildren();for(const [label,fn] of actions){const b=document.createElement('button');b.textContent=label;b.onclick=()=>{dialog.close();fn();};row.append(b);}dialog.showModal();}
 function bag(){show('背包与今日委托',`种子 ${farm.data.seeds} 包 · 草莓 ${farm.data.berries} 份 · 已装箱 ${shipping} 份\n木材 ${economy.state.materials} · 商店 ${economy.state.level} 级\n今日委托：收获 ${Math.min(3,farm.data.harvested)}/3 份草莓。完成后到农场木牌领取奖励。\n床和出货箱在菜地右侧，委托板在左侧，商店沿路向南，港口在海岛东岸。`);}
 function use(){if(!active||dialog.open||cooldown>0)return;const i=nearestPlot();if(i<0){notice('先走到菜地旁边。');return;}if(tool==='hand'){notice('选择锄头、种子、水壶或采收工具。');return;}cooldown=.45;hand.rotation.x=-.9;const target=farm.plots[i].bed.position;player.rotation.y=Math.atan2(player.position.x-target.x,player.position.z-target.z);
  if(tool==='hoe'){if(farm.data.plots[i].stage!=='empty'){notice('这里已经有作物了。');return;}if(tilled[i]){notice('这块地已耕好，可以播种。');return;}if(farm.data.energy<3){notice('体力不足，请回床边睡觉。');return;}tilled[i]=true;farm.data.energy-=3;notice('土地耕好了，按 2 选择种子。');save();return;}
  if(!tilled[i]&&farm.data.plots[i].stage==='empty'){notice('先用锄头耕地。');return;}farm.setTool(tool);farm.act(i);notice(farm.panel.querySelector('[data-message]').textContent);save();
 }
 function nextDay(){const earned=shipping*4;economy.state.coins+=earned;shipping=0;farm.advanceDay();setHour(7);if((farm.data.day-1)%28===0)setSeason(['spring','summer','autumn','winter'][Math.floor((farm.data.day-1)/28)%4]);save();show('新的一天',`昨夜出货收入 ${earned} 贝币。体力已恢复，浇过水的作物长大了。`);}
 function interact(){if(!active||dialog.open)return;
  if(near(...spots.rest)){show('结束今天？','睡觉将保存进度、结算出货并进入第二天。',[['睡到明天',nextDay]]);return;}
  if(near(...spots.shipping)){show('出货箱',`背包有 ${farm.data.berries} 份草莓，今晚每份结算 4 贝币。`,[['放入全部草莓',()=>{shipping+=farm.data.berries;farm.data.berries=0;save();notice('已装箱，睡觉时结算。');}]]);return;}
  if(near(...spots.reward)){show('今日委托','收获至少 3 份草莓，奖励 12 贝币。',[['领取奖励',()=>{farm.panel.querySelector('[data-reward]').click();notice(farm.data.reward?'奖励已领取。':'还没完成今日委托。');}]]);return;}
  if(near(...spots.buy)){if(getHour()<8||getHour()>=18){notice('兔兔商店营业时间：08:00—18:00。');return;}show('兔兔种子商店','草莓种子：每包 2 贝币。',[['购买一包',()=>{farm.panel.querySelector('[data-buy]').click();notice(farm.panel.querySelector('[data-message]').textContent);}]]);return;}
  if(near(...spots.sell)){show('海岛贸易港',economy.shipDocked?'商船已靠港，可以出售草莓。':'商船还未靠港，稍后再来。',[['出售草莓',()=>{farm.panel.querySelector('[data-sell]').click();notice(farm.panel.querySelector('[data-message]').textContent);}]]);return;}
  if(near(...spots.build)){show('海岛工坊','扩建商店需要 12 贝币和 2 份木材，由兔兔家人协助施工。',[['委托建造',()=>{economy.build();notice('已向工坊提出建造请求，可在海岛生活记录查看结果。');}]]);return;}
  const npc=rabbits.find(b=>b.root!==player&&b.root.position.distanceTo(player.position)<2);if(npc){show(npc.name,({小白:'种田回来记得洗干净。豆豆总会帮我梳好毛毛。',豆豆:'我陪着小白，也会帮忙盖房子。今天的农场还顺利吗？',奶糖:'我今天给菜苗浇了水！等会儿要去玩啦。'})[npc.name]);return;}
  use();
 }
 function begin(){if(rabbits[chosen].ride||rabbits[chosen].cycleTrip){notice('等兔兔玩完这一轮再控制它。');return;}economy.step(rabbits[chosen],0,true,false);setMode('player');active=true;document.body.classList.add('playing-town');document.getElementById('panel').hidden=true;const toggle=document.getElementById('panel-toggle');toggle.textContent='☰ 显示面板';toggle.setAttribute('aria-expanded','false');notice('WASD / 摇杆移动 · 1–5 选工具 · 空格使用 · E 互动 · B 背包');}
 function chooseRabbit(index){const b=rabbits[index];if(b.ride||b.cycleTrip||b.bathing){notice('这只兔兔正在忙，稍后再切换。');return;}rabbits[chosen].playerControlled=false;rabbits[chosen].state='search';rabbits[chosen].timer=2;economy.step(b,0,true,false);chosen=index;player=b.root;feet=b.feet;player.add(held);b.path=[];b.target=null;b.playerControlled=getMode()==='player';hud.querySelectorAll('[data-rabbit]').forEach(button=>button.classList.toggle('active',Number(button.dataset.rabbit)===index));keyset.clear();stick={x:0,y:0};notice('现在控制'+b.name);}
 hud.querySelectorAll('[data-rabbit]').forEach(button=>button.onclick=()=>chooseRabbit(Number(button.dataset.rabbit)));chooseRabbit(0);
 start.onclick=begin;hud.querySelector('[data-observe]').onclick=()=>setMode('orbit');hud.querySelector('[data-bag]').onclick=bag;hud.querySelector('[data-use]').onclick=use;hud.querySelector('[data-interact]').onclick=interact;hud.querySelector('[data-close]').onclick=()=>dialog.close();dialog.addEventListener('close',()=>keyset.clear());
 window.addEventListener('keydown',e=>{if(!active||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(['Space','KeyE','KeyB','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(dialog.open)return;keyset.add(e.code);if(e.repeat)return;if(/^Digit[1-5]$/.test(e.code))select(tools[Number(e.code.slice(-1))-1][0]);if(e.code==='Space')use();if(e.code==='KeyE')interact();if(e.code==='KeyB')bag();});window.addEventListener('keyup',e=>keyset.delete(e.code));window.addEventListener('blur',()=>{keyset.clear();stick={x:0,y:0};});
 const joystick=hud.querySelector('[data-stick]'),knob=hud.querySelector('[data-knob]');let pointer=null;function moveStick(e){if(e.pointerId!==pointer)return;const r=joystick.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)/35,y=(e.clientY-r.top-r.height/2)/35,n=Math.max(1,Math.hypot(x,y));stick={x:x/n,y:y/n};knob.style.transform=`translate(${stick.x*28}px,${stick.y*28}px)`;}joystick.onpointerdown=e=>{pointer=e.pointerId;joystick.setPointerCapture(pointer);moveStick(e);};joystick.onpointermove=moveStick;joystick.onpointerup=joystick.onpointercancel=()=>{pointer=null;stick={x:0,y:0};knob.style.transform='';};
 let savedTime=0;return {get player(){return player;},chooseRabbit,begin,use,interact,nextDay,get paused(){return active&&dialog.open;},update(dt){clearedTrees.forEach(o=>o.visible=false);active=getMode()==='player';rabbits.forEach((b,i)=>b.playerControlled=active&&i===chosen);held.visible=active&&tool!=='hand';hud.hidden=!active;document.body.classList.toggle('playing-town',active);if(wasActive!==active){keyset.clear();stick={x:0,y:0};wasActive=active;}if(!active||dialog.open)return;clock+=dt;cooldown=Math.max(0,cooldown-dt);hand.rotation.x*=.8;let dx=(keyset.has('KeyD')||keyset.has('ArrowRight')?1:0)-(keyset.has('KeyA')||keyset.has('ArrowLeft')?1:0)+stick.x,dz=(keyset.has('KeyS')||keyset.has('ArrowDown')?1:0)-(keyset.has('KeyW')||keyset.has('ArrowUp')?1:0)+stick.y;const length=Math.hypot(dx,dz);if(length){dx=dx/Math.max(1,length)*dt*3.4;dz=dz/Math.max(1,length)*dt*3.4;if(!blocked(player.position.x+dx,player.position.z,.25))player.position.x+=dx;if(!blocked(player.position.x,player.position.z+dz,.25))player.position.z+=dz;player.rotation.y=Math.atan2(-dx,-dz);}rabbits[chosen].state=length?'run':'rest';rabbits[chosen].target=null;rabbits[chosen].path=[];player.position.y=groundHeight(player.position.x,player.position.z)+(length?Math.abs(Math.sin(clock*10))*.065:0);feet.forEach((f,i)=>f.rotation.x=length?Math.sin(clock*12+i*Math.PI)*.45:0);ui+=dt;savedTime+=dt;if(savedTime>5){savedTime=0;save();}if(ui>1){ui=0;const h=getHour();hud.querySelector('[data-calendar]').textContent=`${['春','夏','秋','冬'][Math.floor((farm.data.day-1)/28)%4]}季 ${((farm.data.day-1)%28)+1} 日 · ${String(Math.floor(h)).padStart(2,'0')}:${String(Math.floor(h%1*60)).padStart(2,'0')}`;hud.querySelector('[data-energy]').textContent=`体力 ${Math.floor(farm.data.energy)}/100 · 贝币 ${economy.state.coins}`;const spot=Object.keys(spots).find(k=>near(...spots[k]));hud.querySelector('#play-prompt').textContent=spot?'E / 互动：'+({rest:'睡觉',shipping:'出货箱',buy:'种子商店',sell:'商船交易',reward:'委托板',build:'建造工坊'})[spot]:nearestPlot()>=0?'空格 / 使用：'+tools.find(x=>x[0]===tool)[1]:'WASD / 摇杆移动 · E 与兔兔交谈';}},cameraUpdate(){if(getMode()!=='player')return;controls.enabled=false;const p=player.position;camera.position.lerp(new THREE.Vector3(p.x,p.y+7,p.z+9),.15);controls.target.copy(p).add(new THREE.Vector3(0,.5,0));camera.lookAt(controls.target);}};
}
